/**
 * contracts/ — DTOs validados por schema + mappers (camada de revisão humana
 * obrigatória, CLAUDE.md).
 * Módulos chegam pelas issues E1: ENG-234 (session-state + imports),
 * ENG-235 (API/bucket). Os construtores de artefato — manifesto, retorno,
 * relatório e o serializador — saíram na ENG-691: o app não gera artefato.
 * Importa apenas domain/ (+ zod, raiz "zod" somente).
 */
export const CONTRACTS_LAYER = 'contracts' as const;

export {
  fromSessionDto,
  SessionStateDtoSchema,
  toSessionDto,
  type SessionMeta,
  type SessionStateDto,
} from './session-state';
export {
  applyDelivery,
  applyReturn,
  DeliverySchema,
  DELIVERY_NO_GRID_MSG,
  MANIFEST_MISMATCH_MSG,
  ReturnSchema,
  RETURN_NO_GRID_MSG,
  type Delivery,
  type ImportOutcome,
  type ReturnImport,
} from './imports';

// DTOs PROVISÓRIOS do bucket + endpoints (ENG-235) — trocados pelos tipos gerados
// do OpenAPI do tripod-api (ENG-211). Adapters importam SOMENTE os tipos daqui.
export {
  AcoustemeEnvelopeSchema,
  AcoustemeGranularityFramesSchema,
  AudioUrlResponseSchema,
  BucketAudioSchema,
  BucketListResponseSchema,
  GranularityLevelSchema,
  type AcoustemeEnvelope,
  type AcoustemeGranularityFrames,
  type AudioUrlResponse,
  type BucketAudio,
  type BucketAudioBytes,
  type BucketListResponse,
  type GranularityLevel,
} from './bucket';
export {
  ArtifactKindSchema,
  ArtifactResponseSchema,
  ArtifactTripleSchema,
  ArtifactUploadResponseSchema,
  AuthResponseSchema,
  AutosaveRequestSchema,
  AutosaveResponseSchema,
  CreateSessionRequestSchema,
  LockHolderSchema,
  LockStatusSchema,
  MyProjectRolesResponseSchema,
  MyRoleResponseSchema,
  MyRolesResponseSchema,
  OpaqueArtifactSchema,
  ProjectSettingsSchema,
  ProjectSettingsUpdateSchema,
  RenameSessionRequestSchema,
  ResourceListResponseSchema,
  ResourcePathSchema,
  ResourceSummarySchema,
  ResourceUrlResponseSchema,
  RoleSchema,
  SessionListResponseSchema,
  SessionProgressSchema,
  SessionStatePayloadSchema,
  SessionStatusSchema,
  SessionStepSchema,
  SessionSummarySchema,
  TokenRefreshRequestSchema,
  TokenResponseSchema,
  UserLoginRequestSchema,
  UserResponseSchema,
  type ArtifactKind,
  type ArtifactResponse,
  type ArtifactTriple,
  type ArtifactUploadResponse,
  type AuthResponse,
  type AutosaveRequest,
  type AutosaveResponse,
  type CreateSessionRequest,
  type LockHolder,
  type LockStatus,
  type MyProjectRolesResponse,
  type MyRoleResponse,
  type MyRolesResponse,
  type OpaqueArtifact,
  type ProjectSettings,
  type ProjectSettingsUpdate,
  type RenameSessionRequest,
  type ResourceListResponse,
  type ResourcePath,
  type ResourceSummary,
  type ResourceUrlResponse,
  type Role,
  type SessionListResponse,
  type SessionProgress,
  type SessionStatePayload,
  type SessionStatus,
  type SessionStep,
  type SessionSummary,
  type TokenRefreshRequest,
  type TokenResponse,
  type UserLoginRequest,
  type UserResponse,
} from './api';
